name: places
description: Application of Surf Flutter Course

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - res/
    - res/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Black.ttf
        - asset: fonts/Roboto/Roboto-BlackItalic.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
        - asset: fonts/Roboto/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
        - asset: fonts/Roboto/Roboto-Light.ttf
        - asset: fonts/Roboto/Roboto-LightItalic.ttf
        - asset: fonts/Roboto/Roboto-Medium.ttf
        - asset: fonts/Roboto/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Thin.ttf
        - asset: fonts/Roboto/Roboto-ThinItalic.ttf